### ISSUE TITLE
Check checksum.

### ISSUE THREAD

**Issue by haesbaert** [mirage/charrua-core#10]
Currently we ignore the incoming checksum, this should be checked and the packet dropped accordingly.

**Comment by haesbaert** [comment]
Ip done in: 4c9ad1be800da4b4e966e4b3e0fe70228bb77a45

**Comment by yomimono** [comment]
There's an interface for checking transport-layer checksums in `tcpip` now which would be useful here: https://github.com/mirage/mirage-tcpip/pull/277 .

**Comment by hannesm** [comment]
AFAICT this was fixed in https://github.com/mirage/charrua-core/commit/e1ef2ed492a57e0adfdaac45e0d7e86970b54797 !?

**Comment by yomimono** [comment]
AFAICT you're right, thanks @hannesm !

**Comment by haesbaert** [comment]
Not really, only udp checksum is being checked, we’re still missing ip IRC.
